name: AutoPayday
version: '1.0.4'
main: com.giuliocappelli.autoPayday.AutoPayday
author: Giulio Cappelli
api-version: 1.21
depend: [Vault]
description: Plugin that give a pay to online and offline players.

commands:
  autopayday:
    description: AutoPayday config reload
    usage: /<command> reload
    aliases: [apd]

permissions:
  autopayday.reload:
    description: Permission to reload AutoPayday config
    default: op